name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        profile: default
        toolchain: stable
        target: wasm32-unknown-unknown
        default: true
    - name: Build
      run: cargo build --verbose --target wasm32-unknown-unknown
